#
# Module manifest for module 'SecretsManagement.Windows.LAPS'
#
# Generated by: erikgraa
#
# Generated on: 05/15/2025
#

@{
    ModuleVersion = '0.2505.2'
    CompatiblePSEditions = @('Core', 'Desktop')
    GUID = '8b7fa833-7880-48fb-a711-57fbabc0f5b4'
    Author = 'erikgraa'
    Copyright = 'Copyright (c) 2025 erikgraa, licensed under the MIT License.'
    Description = 'A SecretManagement Vault extension for Windows LAPS passwords stored in Active Directory.'
    PowerShellVersion = '5.1'

    NestedModules = @('./SecretManagement.Windows.LAPS.Extension')

    RequiredModules = @('Microsoft.Powershell.SecretManagement')

    PrivateData = @{
        PSData = @{
            Tags = @(
                'ActiveDirectory', 'LAPS', 'PowerShell', 'PowerShell-Core', 'Secret',
                'SecretManagement', 'Vault', 'VaultExtension', 'Microsoft'
            )

            ExternalModuleDependencies = @('ActiveDirectory', 'LAPS')

            ProjectUri     = 'https://github.com/erikgraa/SecretManagement.Windows.LAPS'
            License        = 'https://github.com/erikgraa/SecretManagement.Windows.LAPS/blob/main/LICENSE'
            IconUri        = 'https://raw.githubusercontent.com/erikgraa/SecretManagement.Windows.LAPS/refs/heads/main/images/logo.png'
            ReleaseNotes   = 'https://github.com/erikgraa/SecretManagement.Windows.LAPS'
        }
    }
}